# Generated by Django 4.2.7 on 2025-11-20 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_producto_imagen_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título o mensaje principal del banner.', max_length=100)),
                ('imagen', models.ImageField(help_text='La imagen principal de la promoción (ej: 1920x500).', upload_to='banners/')),
                ('enlace_url', models.URLField(blank=True, help_text='URL a donde dirige el banner (ej: /catalogo/).', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marca si el banner debe mostrarse en la web.')),
                ('orden', models.IntegerField(default=0, help_text='Define la posición en el carrusel (orden ascendente).')),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='appweb.producto')),
            ],
        ),
    ]
