# Generated by Django 4.2.7 on 2025-11-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='plazo_dias',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='pedido',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
